### ISSUE TITLE
How to show animation in flutter app? Any documentation or example?

### ISSUE THREAD

**Issue by deepbhavsar** [jtakakura/spine_flutter#1]
Hi,
I have checked attached example and also checked spine_flutter lib folder. I can not find any specific widget which helpful for showing animation in app? I also can't find proper commenting and documentation. There is default flutter welcome screen has set in example.
Any one had luck with this library?

**Comment by syrokomskyi** [comment]
Try this: https://github.com/signmotion/flutter_spine
Tested on Android.
